// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function normalizeSupabaseValue(value: string | undefined): string | undefined {
    if (typeof value !== 'string') return undefined;

    const trimmed = value.trim();
    if (!trimmed || trimmed === 'undefined' || trimmed === 'null') {
        return undefined;
    }

    return trimmed;
}

function isValidSupabaseUrl(value: string | undefined): value is string {
    if (!value) return false;

    try {
        const url = new URL(value);
        return url.protocol === 'http:' || url.protocol === 'https:';
    } catch {
        return false;
    }
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
    async ({ next }) => {

        const SUPABASE_URL = normalizeSupabaseValue(process.env.SUPABASE_URL);
        const SUPABASE_PUBLISHABLE_KEY = normalizeSupabaseValue(process.env.SUPABASE_PUBLISHABLE_KEY);

        if (!isValidSupabaseUrl(SUPABASE_URL) || !SUPABASE_PUBLISHABLE_KEY) {
            const missing = [
                ...(!isValidSupabaseUrl(SUPABASE_URL) ? ['SUPABASE_URL'] : []),
                ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
            ];
            const message = `Missing or invalid Supabase environment variable(s): ${missing.join(', ')}. Add valid values to your deployment environment.`;
            console.error(`[Supabase] ${message}`);
            throw new Error(message);
        }

        const request = getRequest();

        if (!request?.headers) {
            throw new Error('Unauthorized: No request headers available');
        }

        const authHeader = request.headers.get('authorization');

        if (!authHeader) {
            throw new Error('Unauthorized: No authorization header provided');
        }

        if (!authHeader.startsWith('Bearer ')) {
            throw new Error('Unauthorized: Only Bearer tokens are supported');
        }

        const token = authHeader.replace('Bearer ', '');
        if (!token) {
            throw new Error('Unauthorized: No token provided');
        }

        const supabase = createClient<Database>(
            SUPABASE_URL!,
            SUPABASE_PUBLISHABLE_KEY!,
            {
                global: {
                    headers: {
                        Authorization: `Bearer ${token}`,
                    },
                },
                auth: {
                    storage: undefined,
                    persistSession: false,
                    autoRefreshToken: false,
                },
            }
        );

        const { data, error } = await supabase.auth.getClaims(token);
        if (error || !data?.claims) {
            throw new Error('Unauthorized: Invalid token');
        }

        if (!data.claims.sub) {
            throw new Error('Unauthorized: No user ID found in token');
        }

        return next({
            context: {
                supabase,
                userId: data.claims.sub,
                claims: data.claims,
            },
        });
    },
);
