// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function normalizeSupabaseValue(value: string | undefined): string | undefined {
    if (typeof value !== 'string') return undefined;

    const trimmed = value.trim();
    if (!trimmed || trimmed === 'undefined' || trimmed === 'null') {
        return undefined;
    }

    return trimmed;
}

function isValidSupabaseUrl(value: string | undefined): value is string {
    if (!value) return false;

    try {
        const url = new URL(value);
        return url.protocol === 'http:' || url.protocol === 'https:';
    } catch {
        return false;
    }
}

function createSupabaseAdminClient() {
    const SUPABASE_URL = normalizeSupabaseValue(process.env.SUPABASE_URL);
    const SUPABASE_SERVICE_ROLE_KEY = normalizeSupabaseValue(process.env.SUPABASE_SERVICE_ROLE_KEY);

    if (!isValidSupabaseUrl(SUPABASE_URL) || !SUPABASE_SERVICE_ROLE_KEY) {
        const missing = [
            ...(!isValidSupabaseUrl(SUPABASE_URL) ? ['SUPABASE_URL'] : []),
            ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY'] : []),
        ];
        const message = `Missing or invalid Supabase environment variable(s): ${missing.join(', ')}. Add valid values to your deployment environment.`;
        console.error(`[Supabase] ${message}`);
        throw new Error(message);
    }

    return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
        auth: {
            storage: undefined,
            persistSession: false,
            autoRefreshToken: false,
        }
    });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
    get(_, prop, receiver) {
        if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
        return Reflect.get(_supabaseAdmin, prop, receiver);
    },
});
